version: '3'

services:
  rabbitmq:
    image: "rabbitmq:3.7-management"
    volumes:
      - ./data/queue:/var/lib/rabbitmq/mnesia
    ports:
      - 5672:5672
      - 15672:15672
    hostname: rabbitmq
    container_name: rabbitmq

